---
# tasks file for aws-cli
- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: true

- name: Ensure pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Ensure pip packages are up to date
  ansible.builtin.pip:
    name: pip
    state: latest

- name: Ensure pip packages are up to date
  ansible.builtin.pip:
    name: awscli
    state: latest
    extra_args: "--ignore-installed"

- name: "Ensure user exists"
  ansible.builtin.user:
    name: "{{ user }}"
    state: present

- name: Ensure directories exist
  ansible.builtin.file:
    path: "/home/{{ user }}/.aws"
    state: directory
    owner: {{ user }}
    group: {{ user }}
    mode: "0700"

- name: Ensure awscli is configured
  ansible.builtin.template:
    src: config.j2
    dest: "/home/{{ user }}/.aws/config"
